"""Pure execution v2 domain layer.

No sockets, secrets, production writes, systemd or live broker access.
EV2-03 adds a non-owning same-loop transport kernel; importing it does not
connect sockets or place orders.
EV2-04 adds private event adapters; importing them performs no I/O.
EV2-05 adds the WAL/projector/exporter kernel; importing it does not open
files, start threads/tasks, read env, or initialize Sentry.
EV2-06 adds the execution engine and risk gate; importing it does not
acquire locks, open sockets, drain the WAL, or place orders.
"""

from app.bot.execution.adapters import (
    SCHEMA_VERSION as ADAPTER_SCHEMA_VERSION,
    AdapterBatch,
    AdapterError,
    AdapterIssue,
    AdapterSource,
    PrivateEventAdapter,
)
from app.bot.execution.contracts import (
    SCHEMA_VERSION,
    ContractValidationError,
    ExecutionEvent,
    ExecutionEventType,
    IntentAction,
    LegPlan,
    LegState,
    LegStatus,
    SpreadDirection,
    SpreadState,
    SpreadStatus,
    TradeIntent,
    Venue,
    derive_client_id,
)
from app.bot.execution.exporters import (
    InMemoryExporter,
    MetricsSnapshot,
    SentryEnvelope,
    WalExportCursor,
    map_lifecycle_to_sentry_envelope,
)
from app.bot.execution.state_machine import (
    InvalidTransition,
    apply_event,
    apply_events,
    assert_invariants,
    initial_spread_state,
    is_proven_flat,
    needs_reconciliation,
    opens_allowed,
)
from app.bot.execution.transport import (
    SCHEMA_VERSION as TRANSPORT_SCHEMA_VERSION,
    CachedInstrument,
    DispatchResult,
    DispatchStatus,
    ExecutionTransport,
    FrozenStaticFrame,
    InstrumentCache,
    LoopOwnedTradeSocket,
    PreparedDualLeg,
    TransportError,
    VenueWriteEvidence,
    WriteOutcome,
    declared_owner_loop,
    prepare_dual_leg,
    unsigned_frame_finalizer,
)
from app.bot.execution.engine import (
    SCHEMA_VERSION as ENGINE_SCHEMA_VERSION,
    MAX_NOTIONAL_USDT,
    EngineError,
    ExecutionEngine,
    IngestResult,
    ReadinessSnapshot,
    RiskPolicy,
    SubmitResult,
    SubmitStatus,
)
from app.bot.execution.ownership import (
    SCHEMA_VERSION as OWNERSHIP_SCHEMA_VERSION,
    FileOwnershipFence,
    OwnershipError,
)
from app.bot.execution.wal import (
    SCHEMA_VERSION as WAL_SCHEMA_VERSION,
    SUBMIT_WORST_CASE_EVENTS,
    ExecutionWal,
    InMemoryProjector,
    ProjectionAck,
    ReplayResult,
    WalAppendAck,
    WalDurableAck,
    WalError,
    WalHealth,
    WalIntegrityError,
    WalRecord,
    admission_capacity_ok,
)

__all__ = [
    "ADAPTER_SCHEMA_VERSION",
    "ENGINE_SCHEMA_VERSION",
    "MAX_NOTIONAL_USDT",
    "OWNERSHIP_SCHEMA_VERSION",
    "SCHEMA_VERSION",
    "SUBMIT_WORST_CASE_EVENTS",
    "TRANSPORT_SCHEMA_VERSION",
    "WAL_SCHEMA_VERSION",
    "AdapterBatch",
    "AdapterError",
    "AdapterIssue",
    "AdapterSource",
    "CachedInstrument",
    "ContractValidationError",
    "DispatchResult",
    "DispatchStatus",
    "EngineError",
    "ExecutionEngine",
    "ExecutionEvent",
    "ExecutionEventType",
    "ExecutionTransport",
    "ExecutionWal",
    "FileOwnershipFence",
    "FrozenStaticFrame",
    "InMemoryExporter",
    "InMemoryProjector",
    "IngestResult",
    "InstrumentCache",
    "IntentAction",
    "InvalidTransition",
    "LegPlan",
    "LegState",
    "LegStatus",
    "LoopOwnedTradeSocket",
    "MetricsSnapshot",
    "OwnershipError",
    "PreparedDualLeg",
    "PrivateEventAdapter",
    "ProjectionAck",
    "ReadinessSnapshot",
    "RiskPolicy",
    "ReplayResult",
    "SentryEnvelope",
    "SubmitResult",
    "SubmitStatus",
    "SpreadDirection",
    "SpreadState",
    "SpreadStatus",
    "TradeIntent",
    "TransportError",
    "Venue",
    "VenueWriteEvidence",
    "WalAppendAck",
    "WalDurableAck",
    "WalError",
    "WalExportCursor",
    "WalHealth",
    "WalIntegrityError",
    "WalRecord",
    "WriteOutcome",
    "admission_capacity_ok",
    "apply_event",
    "apply_events",
    "assert_invariants",
    "declared_owner_loop",
    "derive_client_id",
    "initial_spread_state",
    "is_proven_flat",
    "map_lifecycle_to_sentry_envelope",
    "needs_reconciliation",
    "opens_allowed",
    "prepare_dual_leg",
    "unsigned_frame_finalizer",
]
